pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.ocean.pangeo.io
        letsencrypt:
          contactEmail: raphael.dussin@gmail.com
    hub:
      service:
        loadBalancerIP: 35.238.36.78
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false