pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.ocean.pangeo.io
        letsencrypt:
          contactEmail: raphael.dussin@gmail.com
      service:
        loadBalancerIP: 35.238.36.78
