pangeo:
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
      corePods:
        nodeAffinity:
          matchNodePurpose: require
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: home
            mountPath: /home/jovyan
            subPath: "home/{username}"
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "home/{username}"
        homeMountPath: /home/jovyan
      cloudMetadata:
        enabled: false
      cpu:
        limit: 4
        guarantee: 1.6
      memory:
        limit: 14G
        guarantee: 1G
    hub:
      #resources:
        #requests:
          #cpu: "0.5"
          #memory: 1Gi
        #limits:
          #cpu: "1.25"
          #memory: 1Gi
      extraConfig:
        azure: |
          c.KubeSpawner.start_timeout = 60 * 20 # 20-minute timeout for Azure (!)
        #profile_list: |
        #  c.KubeSpawner.profile_list = [
        #    {
        #        'display_name': 'minimal (0.2 Cores, 1 GB RAM)',
        #        'kubespawner_override': {
        #            'cpu_limit': 0.2,
        #            'cpu_guarantee': 0.2,
        #            'mem_limit': '1G',
        #            'mem_guarantee': '1G',
        #        }
        #    }
        #  ]
          #  {
          #      'display_name': 'small (n1-highmem-2 | 2 cores, 12GB)',
          #      'kubespawner_override': {
          #          'cpu_limit': 2,
          #          'cpu_guarantee': 2,
          #          'mem_limit': '12G',
          #          'mem_guarantee': '12G',
          #      }
          #  },

          #  {
          #      'display_name': 'standard (n1-highmem-4 | 4 cores, 24GB)',
          #      'kubespawner_override': {
          #          'cpu_limit': 4,
          #          'cpu_guarantee': 4,
          #          'mem_limit': '24G',
          #          'mem_guarantee': '24G',
          #      }
          #  }
          #]
        customPodHook: |
          c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'ooi..pangeo.io',
            'pangeo_hub_subtitle': 'a community hub for geoscience research',
            'pangeo_welcome': """Welcome to ooi.pangeo.io. This Pangeo deployment lives in Azure Cloud region <code>eastus</code>. It is maintained by the <a href="http://pangeo.io">Pangeo project</a> and supported by a grant from Microsoft Corporation. The hub's configuration is stored in the github repository <a href="https://github.com/pangeo-data/pangeo-cloud-federation/">https://github.com/pangeo-data/pangeo-cloud-federation/</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation//issues">github issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-templates
          gitRepo:
            repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
            revision: "0c799bb2f880c8b516dcf90e2a90328078d60c25"
      extraVolumeMounts:
        - mountPath: /usr/local/share/jupyterhub/custom_templates
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/templates"
        - mountPath: /usr/local/share/jupyterhub/static/extra-assets
          name: custom-templates
          subPath: "pangeo-custom-jupyterhub-templates/extra-assets"
    auth:
      github:
        orgWhitelist:
          - ooicloud
      #    - pangeo-data
      #    - pydata
      #    - dask
      #    - xarray-dev
      #    - jupyterhub
      #    - informatics-lab
      scopes:
        - "read:org"
        - "read:user"
      admin:
        access: true
        users:
          - tjcrone
          - daxsoule
          - mrocklin
          - jhamman
          - rabernat
          - yuvipanda
homeDirectories:
  nfs:
    enabled: true
    serverPath: "/mnt/ooicloud"
    serverIP: 10.0.0.4
