pangeo:
  jupyterhub:
    proxy:
      https:
        enabled: false
        #hosts:
        #- ooi.pangeo.io
        #letsencrypt:
        #  contactEmail: tjcrone@gmail.com
      service:
        annotations: {'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'ooi-pangeo'}
        loadBalancerIP: 23.96.23.164
