pangeo:
  jupyterhub:
    proxy:
      https:
        enabled: false
        #hosts:
        #- staging.ooi.pangeo.io
        #letsencrypt:
        #  contactEmail: tjcrone@gmail.com
      service:
        loadBalancerIP: 40.121.196.15
