pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.hydro.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: 35.238.0.56
