name: Build and Deploy
on:
  push:
    branches:
      - staging
      #- prod

jobs:
  build:
    name:
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: docker://yuvipanda/hubploy:20200826083951674280
          name: Uunlock git-crypt Secrets
          env:
            GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
          with:
            entrypoint: /bin/bash
            args: -c "echo ${GIT_CRYPT_KEY} | base64 -d | git crypt unlock - && git crypt status"
        - uses: docker://yuvipanda/hubploy:20200826083951674280
          name: Build & Push AWS image if needed
          with:
            args: -c "build icesat2 --check-registry --push"
        - uses: docker://yuvipanda/hubploy:20200826083951674280
          name: Setup Helm
          with:
            entrypoint: /bin/bash
            args: -c "helm init --client-only && helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ && helm repo update"
        - uses: docker://yuvipanda/hubploy:20200826083951674280
          name: Deploy AWS Staging Hub
          if: github.ref == 'refs/heads/staging'
          with:
            args: deploy icesat2 pangeo-deploy staging --timeout 1200s --cleanup-on-fail
        #- uses: docker://yuvipanda/hubploy:20200826083951674280
        #  name: Deploy AWS Production Hub
        #  if: github.ref == 'refs/heads/prod'
        #  with:
        #    args: deploy icesat2 pangeo-deploy prod --timeout 1200s --cleanup-on-fail
