name: Build and Deploy
on:
  push:
    branches:
      - staging
      #- prod

env:
  HUBPLOY_IMAGE: docker://yuvipanda/hubploy:20200826083951674280

jobs:
  build:
    name:
      # This job runs on Linux
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: $HUBPLOY_IMAGE
          name: Unlock git-crypt Secrets
          env:
            GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
          with:
            entrypoint: /bin/bash
            args: -c "echo ${GIT_CRYPT_KEY} | base64 -d | git crypt unlock - && git crypt status"
        - uses: $HUBPLOY_IMAGE
          name: Build & Push AWS Image if Needed
          with:
            args: -c "build icesat2 --check-registry --push"
        - uses: $HUBPLOY_IMAGE
          name: Setup Helm
          with:
            entrypoint: /bin/bash
            args: >
              -c "helm init --client-only && \
              helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/ &&\
              helm repo add dask https://helm.dask.org/
              helm repo add dask-gateway https://dask.org/dask-gateway-helm-repo/ &&\
              helm repo add stable https://kubernetes-charts.storage.googleapis.com &&\
              helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx &&\
              helm repo add prometheus-operator https://kubernetes-charts.storage.googleapis.com &&\
              helm repo update"
        - uses: $HUBPLOY_IMAGE
          name: Deploy AWS Staging Hub
          if: github.ref == 'refs/heads/staging'
          with:
            args: deploy icesat2 pangeo-deploy staging --timeout 1200s --cleanup-on-fail
        #- uses: $HUBPLOY_IMAGE
        #  name: Deploy AWS Production Hub
        #  if: github.ref == 'refs/heads/prod'
        #  with:
        #    args: deploy icesat2 pangeo-deploy prod --timeout 1200s --cleanup-on-fail
