distributed:
  logging:
    bokeh: critical

  dashboard:
    link: /user/{JUPYTERHUB_USER}/proxy/{port}/status

  admin:
    tick:
      limit: 5s

kubernetes:
  worker-template:
    metadata:
    spec:
      restartPolicy: Never
      nodeSelector:
      agentpool: "notebook"
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '1'
          - --no-bokeh
          - --memory-limit
          - "2GB"
          - --death-timeout
          - '60'
        image: ${JUPYTER_IMAGE_SPEC}
        name: dask-${JUPYTERHUB_USER}
        resources:
          limits:
            cpu: 0.4
            memory: "2G"
          requests:
            cpu: 0.4
            memory: "2G"

labextension:
  factory:
    module: dask_kubernetes
    class: KubeCluster
    args: []
    kwargs: {}
