name: pangeo
channels:
  - conda-forge
dependencies:
  - erddapy
  - pip
  - pip:
    - azure
    - git+https://github.com/ooicloud/ooi-opendata.git@master
    - git+https://github.com/pydata/xarray.git@0ef9aa3abae55833e4431d690bc55c5b5a44911b
