name: pangeo
channels:
  - conda-forge
dependencies:
  - av
  - erddapy
  - pip
  - pip:
    - azure
    - git+https://github.com/ooicloud/ooi-opendata.git@bad61bf649ae5b189ff14fae06b567b25a8b2e47
    - pycamhd
