pangeo:
  jupyterhub:
    singleuser:
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 1
      memory:
        limit: 14G
        guarantee: 4G
    auth:
      github:
        org_whitelist:
          - pangeo-data
          - pydata
          - dask
          - xarray-dev
          - jupyterhub
          - informatics-lab
      admin:
        access: true
        users:
          - mrocklin
          - jhamman
          - rabernat
          - yuvipanda
          - choldgraf
          - jacobtomlinson
          - dsludwig
          - rsignell-usgs
  homeDirectories:
    nfs:
      # Output from gcloud beta filestore instances describe dev-home --location=us-central1-b
      serverIP: 10.171.161.186
      serverName: test
