version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic-scm
      
    working_directory: ~/repo
    steps:
      - run:
          name: Install base apt packages
          command: |
            apt-get update --yes -qq
            apt-get install --yes -qq python3 python3-venv git-crypt jq
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade -r requirements.txt
            # Install repo2docker explicitly since we want a higher version than the released
            # Can't put this in requirements.txt since pip doesn't seem to realize this is a newer version
            # This branch combines upstream/master with yuvipanda/julia-requirements-no-verseioneer
            pip install --upgrade --force-reinstall git+https://github.com/jhamman/repo2docker@pangeo_hubploy
            echo 'export PATH="${HOME}/repo/venv/bin:$PATH"' >> ${BASH_ENV}
      - setup_remote_docker
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Determine range of commits we are building
          command: |
              # CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
              COMMIT_RANGE=$(./.circleci/get-commit-range.py)
              echo ${COMMIT_RANGE}
              echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}
      - run:
          name: Test building dev.pangeo.io image if needed
          command: |
            hubploy build dev --commit-range ${COMMIT_RANGE}
          environment:
            PYTHONIOENCODING: utf-8

      - run:
          name: Test building ocean.pangeo.io image if needed
          command: |
            hubploy build ocean --commit-range ${COMMIT_RANGE}
          environment:
            PYTHONIOENCODING: utf-8
  deploy:
    docker:
      - image: buildpack-deps:bionic-scm
    working_directory: ~/repo
    steps:
      - run:
          name: Install base apt packages
          command: |
            apt-get update -qq --yes
            apt-get install -qq --yes python3 python3-venv git-crypt
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-gcloud-226-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-gcloud-226-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade -r requirements.txt

            # Install repo2docker explicitly since we want a higher version than the released
            # Can't put this in requirements.txt since pip doesn't seem to realize this is a newer version
            # This branch combines upstream/master with yuvipanda/julia-requirements-no-verseioneer
            pip install --upgrade --force-reinstall git+https://github.com/jhamman/repo2docker@pangeo_hubploy
            echo 'export PATH="${HOME}/repo/venv/bin:$PATH"' >> ${BASH_ENV}

            curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-226.0.0-linux-x86_64.tar.gz | tar -C venv/ -xzf -
            # Be careful with quote ordering here. ${PATH} must not be expanded
            # Don't use ~ here - bash can interpret PATHs containing ~, but most other things can't.
            # Always use full PATHs in PATH!
            echo 'export PATH="${HOME}/repo/venv/bin:${HOME}/repo/venv/google-cloud-sdk/bin:${PATH}"' >> ${BASH_ENV}

      - setup_remote_docker
        
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-gcloud-226-{{ checksum "requirements.txt" }}

      - run:
          name: Determine range of commits we are building
          command: |
              # CircleCI doesn't have equivalent to Travis' COMMIT_RANGE
              COMMIT_RANGE=$(./.circleci/get-commit-range.py)
              echo ${COMMIT_RANGE}
              echo "export COMMIT_RANGE='${COMMIT_RANGE}'" >> ${BASH_ENV}

      - run:
          name: Unlock our secrets
          command: |
            echo "${GIT_CRYPT_KEY}" | base64 -d > ~/repo/key
            git crypt unlock ~/repo/key
            rm ~/repo/key

      - run:
          name: Build dev.pangeo.io image if needed
          command: |
            hubploy build dev --commit-range ${COMMIT_RANGE} --push
          environment:
            PYTHONIOENCODING: utf-8

      - run:
          name: Build ocean.pangeo.io image if needed
          command: |
            hubploy build ocean --commit-range ${COMMIT_RANGE} --push
          environment:
            PYTHONIOENCODING: utf-8

      - run:
          name: Install helm
          command: |
            curl https://storage.googleapis.com/kubernetes-helm/helm-v2.10.0-linux-amd64.tar.gz | \
              tar -xzf -
            mv linux-amd64/helm /usr/local/bin
            helm init --client-only
            helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
            helm repo update

      - run:
          name: Deploy dev.pangeo.io
          command: |
            hubploy deploy dev pangeo-deploy ${CIRCLE_BRANCH}

      - run:
          name: Deploy ocean.pangeo.io
          command: |
            hubploy deploy ocean pangeo-deploy ${CIRCLE_BRANCH}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - staging
                - prod
      - deploy:
          filters:
            branches:
              only:
                - staging
                - prod
