name: icesat2
channels:
  - conda-forge
dependencies:
  - conda 
  - ipykernel 
  - nb_conda_kernels 
  - curl
  - libgdal 
  - boto3 
  - awscli
  - geopandas 
  - pip:
    - rio-cogeo
    - sat-search
