daskhub:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.us-central1-b.gcp.pangeo.io
        letsencrypt:
          contactEmail: rpa@ldeo.columbia.edu 
      service:
        loadBalancerIP: 34.69.173.244
    hub:
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
        limits:
          cpu: "0.1"
          memory: 0.25Gi
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://staging.us-central1-b.gcp.pangeo.io/services/dask-gateway/"

    scheduling:
      userScheduler:
        enabled: false
