pangeo:
  jupyterhub:
    singleuser:
      storage:
        type: "static"
        static:
          pvcName: "efs-persist"
          subPath: 'home/{username}'
      extraEnv:
        CHOWN_HOME: 'yes'
      uid: 0
      fsGid: 0
      cloudMetadata:
        enabled: true
      cpu:
        limit: 4
        guarantee: 1
      memory:
        limit: 14G
        guarantee: 4G
    auth:
      github:
        callbackUrl: "https://staging.icesat2.pangeo.io/hub/oauth_callback"
        orgWhitelist:
          - "ICESAT-2HackWeek"
          - "pangeo-data"
      scopes:
        - "read:user"
      admin:
        access: true
        users:
          - scottyhq
          - jhamman
          - apawloski
          - amanda-tan
homeDirectories:
  nfs:
    enabled: false
