# Leave commented for first build, then uncomment and add loadBalancerIP
daskhub:
  jupyterhub:
    hub:
      extraEnv:
        OAUTH_CALLBACK_URL: "https://aws-uswest2.pangeo.io/hub/oauth_callback"
    proxy:
      https:
        hosts:
          - aws-uswest2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
