pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.icesat2.pangeo.io
        letsencrypt:
          contactEmail: scottyh@uw.edu
      service:
        loadBalancerIP: CHANGE_AFTER_FIRST_DEPLOYMENT
