name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - jupyterthemes
  - dask
  - xarray
  - ipyleaflet
  - seaborn
  - cartopy
  - pandas
  - geopandas
  - hvplot
  - netCDF4
  - bokeh
  - pip:
    - git+https://github.com/arbennett/pysumma.git@whw2019
    - hs_restclient
