name: pangeo
channels:
  - conda-forge
dependencies:
  - conda>=4.6.8
  - python=3.7
  - numpy
  - matplotlib
  - dask
  - xarray>0.10.9
  - ipyleaflet
  - seaborn
  - cartopy
  - pandas
  - geopandas
  - hvplot
  - netCDF4
  - bokeh
  - pip:
    - git+https://github.com/arbennett/pysumma.git@4ade1ccdc423bdbcde6c4e13c71a517bfc71d792
    - hs_restclient
    - nbgitpuller
