jupyterhub:
  singleuser:
    storage:
      dynamic:
        storageClass: gp2
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
  auth:
    github:
      org_whitelist:
        - pangeo-data
    admin:
      access: true
      users:
        - scottyhq
        - jhamman
        - apawloski
        - amanda-tan
