pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.nasa.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
      service:
        loadBalancerIP: aa551d9683ec511e9bf3f12e07d3d23e-514376866.us-east-1.elb.amazonaws.com
