# Leave commented for first build, then uncomment and add loadBalancerIP
# pangeo:
#   jupyterhub:
#     proxy:
#       nodeSelector:
#         alpha.eksctl.io/nodegroup-name: hub
#       https:
#         hosts:
#         - staging.nasa.pangeo.io
#         letsencrypt:
#           contactEmail: scottyh@uw.edu
#       service:
#         loadBalancerIP:
#     auth:
#       github:
#         callbackUrl: "https://staging.nasa.pangeo.io/hub/oauth_callback"
