name: pangeo
channels:
  - conda-forge
dependencies:
  - altair
  - basemap
  - cc-plugin-ncei
  - ciso
  - cmocean
  - compliance-checker
  - ctd
  - descartes
  - erddapy
  - folium
  - fsspec
  - geolinks
  - gridgeo
  - ioos-tools
  - owslib
  - palettable
  - pocean-core
  - podaacpy
  - retrying
  - seaborn
  - sympy
  - unyt
  - utide
  - xhistogram
  - xlrd
  - xmitgcm>=0.4.1
