name: pangeo
channels:
  - conda-forge
dependencies:
  - cc-plugin-ncei
  - ciso
  - compliance-checker
  - ctd
  - geolinks
  - gridgeo
  - ioos-tools
  - pocean-core
  - podaacpy
  - pyoos
  - retrying
  - unyt
  - utide
  - xlrd
  - xmitgcm>=0.4.1
  - pip:
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/pydata/xarray.git
