jupyterhub:
  singleuser:
    initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: home
          mountPath: /home/jovyan
          subPath: "home/pangeo-users/{username}"
    storage:
      type: static
      static:
        pvcName: home-nfs
        subPath: "home/pangeo-users/{username}"
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
  extraConfig:
      profile_list: |
        c.KubeSpawner.profile_list = [
          {
              'display_name': 'base-notebook - small (n1-highmem-2 | 2 cores, 12GB)',
              'kubespawner_override': {
                  'image': 'pangeo/base-notebook:latest',
              }
          },
          {
              'display_name': 'pangeo-notebook - small (n1-highmem-2 | 2 cores, 12GB)',
              'kubespawner_override': {
                  'image': 'pangeo/pangeo-notebook:latest',
              }
          },
        ]
  auth:
    github:
      org_whitelist:
        - pangeo-data
        - pydata
        - dask
        - xarray-dev
        - jupyterhub
        - informatics-lab
    admin:
      access: true
      users:
        - mrocklin
        - jhamman
        - rabernat
        - yuvipanda
        - choldgraf
        - jacobtomlinson
        - dsludwig
        - rsignell-usgs
homeDirectories:
  nfs:
    # Output from gcloud beta filestore instances describe dev-home --location=us-central1-b
    serverIP: 10.171.161.186
    serverName: test
