pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
          - staging.hub.pangeo.io
        letsencrypt:
          contactEmail: jhamman@ucar.edu
    hub:
      service:
        loadBalancerIP: 35.232.186.70
      resources:
        requests:
          cpu: "0.1"
          memory: 0.25Gi
    scheduling:
      userScheduler:
        enabled: false
